import TOCInline from 'pliny/ui/TOCInline'
import Pre from 'pliny/ui/Pre'
import BlogNewsletterForm from 'pliny/ui/BlogNewsletterForm'
import type { MDXComponents } from 'mdx/types'
import Image from './Image'
import CustomLink from './Link'
import TableWrapper from './TableWrapper'

// Suppress hydration warnings for math elements generated by remark-math
const InlineMath = ({ children }: { children: React.ReactNode }) => (
  <span className="math inline" suppressHydrationWarning>
    {children}
  </span>
)
const BlockMath = ({ children }: { children: React.ReactNode }) => (
  <div className="math block" suppressHydrationWarning>
    {children}
  </div>
)

export const components: MDXComponents = {
  Image,
  TOCInline,
  a: CustomLink,
  pre: Pre,
  table: TableWrapper,
  BlogNewsletterForm,
  inlineMath: InlineMath,
  blockMath: BlockMath,
}
